### PR TITLE
Add indicator/reference element

### PR DESCRIPTION
**Pull request by HerbCaudill**
Phase 1 of changes to the result element: Add indicator/reference element (includes should-pass & should-fail tests).

### CODE REVIEW

**Comment by rolfkleef** [comment]
Hi Herb, this is still open I see... 

A question: you describe the reference as _"There can be multiple references for each each indicator - for example, if the same indicator is referenced in multiple indicator vocabularies"_. Do you mean an indicator could have multiple references within a single vocabulary as well? My instinct says: no more than one reference per vocabulary.

(Also minor: the word 'each' is doubled in that part of the description)

**Comment by HerbCaudill** [comment]
Hi, Rolf. Just saw your note. I'd agree that it would only make sense to allow multiple references from different vocabularies. I don't know of a way to enforce that in XSD, though.

**Comment by rolfkleef** [comment]
I don't think you can do it in XSD. There are a few more constraints that can't be enforced in schemas, but there has been work on ["rule sets"](https://github.com/IATI/IATI-Rulesets) that allow some extra checks on a data file that validates against the schema. The [Public Validator](https://github.com/IATI/IATI-Public-Validator) can check a rule set.

I don't know if the check can be written in such a rule, but the rule set engine can be extended.

**Comment by amy-silcock** [comment]
My understanding of the issue is that you can have multiple references, but must only have one reference from each vocabulary.

**Comment by amy-silcock** [comment]
This is implemented in the Standard:

image

**Pull request closed without merging**
