### PR TITLE
Result element integration

### PR DESCRIPTION
**Pull request by allthatilk**
Integration branch for `result` element changes.

### CODE REVIEW

**Comment by hayfield** [comment]
I have not been involved in the creation of this. As such, without a clear list of issues that this fixes (and the corresponding PRs), I cannot reasonably review this PR as it stands since it's so big.

**Comment by allthatilk** [comment]
@hayfield  here you go: 
https://github.com/IATI/IATI-Schemas/issues/366
https://github.com/IATI/IATI-Schemas/issues/365
https://github.com/IATI/IATI-Schemas/issues/364
https://github.com/IATI/IATI-Schemas/issues/363
https://github.com/IATI/IATI-Schemas/issues/362
https://github.com/IATI/IATI-Schemas/issues/359
https://github.com/IATI/IATI-Schemas/issues/354
https://github.com/IATI/IATI-Schemas/issues/353
https://github.com/IATI/IATI-Schemas/issues/352
https://github.com/IATI/IATI-Schemas/issues/347

**Comment by allthatilk** [comment]
there may be some document link stuff too but all that stuff is contained in one issue on its own anyway so will be easy to find if you need it

**Comment by allthatilk** [comment]
@hayfield [try this](http://thumbpress.com/wp-content/uploads/2014/06/funny-potato-tiny-cheer-pink1.jpg)

**Comment by hayfield** [comment]
#353 is not complete. If this is to be merged, the incomplete stuff in there needs extracting into other issues.

IATI/IATI-Rulesets#51 and IATI/IATI-Rulesets#52 are 2/3 of those things, though the Guideline addition should also be noted somewhere.

**Comment by hayfield** [comment]
Once #405 is merged, this PR should be complete and ready for approval / merging.

**Comment by dalepotter** [comment]
#405 is now merged, so marking this as complete.

**Review by dalepotter — APPROVED** [review]
This is an integration branch, so all code should have been fully reviewed on feature branches. However, I have done a spot check on 50% of the issues noted in [Imogen's post](https://github.com/IATI/IATI-Schemas/pull/394#issuecomment-352033773) and found no issues. Therefore, I'm approving this...

**Pull request merged**
